GET http://localhost:4000/

###


GET http://localhost:4000/data


###


GET http://localhost:4000/data/6


###


POST http://localhost:4000/newObject
Content-Type: application/json

{
    "id": 6,
    "name": "Jacket",
    "color": "Blue",
    "year": "9527"
}

###j

PUT http://localhost:4000/data/toModify/4
Content-Type: application/json

{
    "name": "Black",
    "cplo": "Red",
    "ykkk": "1427"
}

###

DELETE http://localhost:4000/data/toDelete/6